<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'avatar' => '662d2caf2527a_ali-morshedlou-WMD64tMfc4k-unsplash.jpg',
                'firstName' => 'khalid',
                'lastName' => 'khalid',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'khalid@gmail.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => '2024-04-27 16:27:20',
                'password' => '$2y$12$vPF2RqcUDH6YD06xdb17KOUHiePrA.t9iu7B9/08jfGeg0TDWOF9.',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 16:26:55',
                'updated_at' => '2024-04-27 16:49:51',
            ),
           /*  1 => 
            array (
                'id' => 2,
                'avatar' => '662d2e1f869c5_Bouton modifier - Icônes interface gratuites.png',
                'firstName' => 'Marshall',
                'lastName' => 'Leach',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 0,
                'email' => 'miqerev@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$yMvMW3JwM52GFhJEu3m7Jepm3KJ.SnoxTeG.DjTyr6CU8ygUQRh0i',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 16:33:42',
                'updated_at' => '2024-04-27 16:55:59',
            ),
            2 => 
            array (
                'id' => 6,
                'avatar' => '662d2ceb6fc5a_christian-buehner-DItYlc26zVI-unsplash.jpg',
                'firstName' => 'Erich',
                'lastName' => 'Roach',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 0,
                'email' => 'noxan@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$35BvGvtnBukalITbg5TzqOrPUGIRfmDIg8l1fYUvKBlP49vsczbu.',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 16:50:51',
                'updated_at' => '2024-04-27 16:50:51',
            ),
            3 => 
            array (
                'id' => 7,
                'avatar' => '662d2e950e654_50-Off-Discount-PNG.png',
                'firstName' => 'Jaden',
                'lastName' => 'Miranda',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 0,
                'email' => 'xigexiqyfo@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$cP9GhAHBVbxNQL6uzgROc.ID/LSxXfsJil13vjjUlIGQs.dfvM/5W',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 16:57:19',
                'updated_at' => '2024-04-27 16:57:57',
            ),
            4 => 
            array (
                'id' => 8,
                'avatar' => '662f6e1d9693b_glowup.png',
                'firstName' => 'Celeste',
                'lastName' => 'Wynn',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'amine@gmail.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$YVZk6Q.IQtEkxA2F6fnZD.Qw55psX.XSpTSyegTJEpwHUf.NAc/x.',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:01:21',
                'updated_at' => '2024-04-29 09:53:33',
            ),
            5 => 
            array (
                'id' => 9,
                'avatar' => '662d2f93c124f_download.png',
                'firstName' => 'Clayton',
                'lastName' => 'Wolfe',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'xugu@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$zbZWiHz7XP7dn7XpOBuEKuCcEd8k6xWTkPeOHiesWqfriKEl2eDli',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:02:12',
                'updated_at' => '2024-04-27 17:02:12',
            ),
            6 => 
            array (
                'id' => 10,
                'avatar' => '662d2fb642ac0_download.png',
                'firstName' => 'Plato',
                'lastName' => 'Hensley',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'repehoxun@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$qXLnwGpFE0ijE3vT1VCp9usG0BKaXnsMODLHl5xGgQYS2.Z2JAXhO',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:02:46',
                'updated_at' => '2024-04-27 17:02:46',
            ),
            7 => 
            array (
                'id' => 11,
                'avatar' => '662d2fde7616a_Free User SVG, PNG Icon, Symbol. Download Image..png',
                'firstName' => 'Quintessa',
                'lastName' => 'House',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'rywemuxeha@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$g0GcbaRkNebaoS.Fpnbov.70qFhY8xRPS72LEbf9ndwzo4ZNDics.',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:03:27',
                'updated_at' => '2024-04-27 17:03:27',
            ),
            8 => 
            array (
                'id' => 12,
                'avatar' => '662d3014949c9_Free User SVG, PNG Icon, Symbol. Download Image..png',
                'firstName' => 'Garrett',
                'lastName' => 'Yates',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'bebobo@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$6Sgixy0aX2T8zCX/kGqsZ.jEmfeIiKaPkao58kzhIxaR3d5kO4wBS',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:04:21',
                'updated_at' => '2024-04-27 17:04:21',
            ),
            9 => 
            array (
                'id' => 13,
                'avatar' => '662d30dad9910_freestocks-9UVmlIb0wJU-unsplash.jpg',
                'firstName' => 'Jennifer',
                'lastName' => 'Riggs',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'tuwofypoze@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Qly2CMXemfm.NwnLBL2./uKZ9iRFlSVkQUZ3KxhXprQ.x.oSRGBRy',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:07:39',
                'updated_at' => '2024-04-27 17:07:39',
            ),
            10 => 
            array (
                'id' => 14,
                'avatar' => '662d3171b7431_default-avatar-profile-icon-of-social-media-user-photo-image-vector.jpg',
                'firstName' => 'Graiden',
                'lastName' => 'Jacobson',
                'is_login' => 0,
                'is_popular' => 1,
                'password_change' => 1,
                'email' => 'zolira@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$1cWl4XbYYUrGoJEeTpODH.KNyO0y6L.8uX/.VJQ3iC6uQfryZbaEu',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:10:10',
                'updated_at' => '2024-04-27 17:10:10',
            ),
            11 => 
            array (
                'id' => 15,
                'avatar' => '662d31b77827e_img1.jpeg',
                'firstName' => 'Rogan',
                'lastName' => 'Waters',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'milul@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$faoFZZOO7ynGAw/f7kQNFOO06Um.YIHDmr4CiypxVSXTllkfB8GRa',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:11:20',
                'updated_at' => '2024-04-27 17:11:20',
            ),
            12 => 
            array (
                'id' => 16,
                'avatar' => '662d31dcb6411_img2.jpg',
                'firstName' => 'Karly',
                'lastName' => 'Woodard',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'panosyza@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$ugtfJhSZ70GSz4k4nQOiZOxnRZY/BdpgxpdVHVvWwUuaaS7kHraii',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:11:57',
                'updated_at' => '2024-04-27 17:11:57',
            ),
            13 => 
            array (
                'id' => 17,
                'avatar' => '662d31fab36fb_ludovic-migneault-EZ4TYgXPNWk-unsplash.jpg',
                'firstName' => 'Holmes',
                'lastName' => 'Howell',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'fugidydom@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$6yIJSH6AIPYSIHEc5iVY1.EinHR5/VmiDLiVjisFRZj.cFu0yn0kW',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:12:27',
                'updated_at' => '2024-04-27 17:12:27',
            ),
            14 => 
            array (
                'id' => 18,
                'avatar' => '662d3232e6160_irene-strong-v2aKnjMbP_k-unsplash.jpg',
                'firstName' => 'Anjolie',
                'lastName' => 'Watts',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'nywowyle@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$GynLtjgIP/upMHrFlg4BjuZbWllx5YztNUVYtOCVQqU5/B/5As1/q',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:13:23',
                'updated_at' => '2024-04-27 17:13:23',
            ),
            15 => 
            array (
                'id' => 19,
                'avatar' => '662d32633de5d_istockphoto-499517325-612x612.jpg',
                'firstName' => 'Jane',
                'lastName' => 'Savage',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'huwyguh@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Cd9qDI0nLmn1BlMdqVnPmuYLZFrRcp5ENPZgkD79AvJi0n9zq4BUi',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:14:11',
                'updated_at' => '2024-04-27 17:14:11',
            ),
            16 => 
            array (
                'id' => 20,
                'avatar' => '662d328e307f4_marie-michele-bouchard-3U9BCWHMhUw-unsplash.jpg',
                'firstName' => 'Neve',
                'lastName' => 'Fowler',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'meri@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$z6MdlWlddg8TuwisdOubCeQyOoyGnRENJ.ofaN.P5DygJwuiBcoae',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:14:54',
                'updated_at' => '2024-04-27 17:14:54',
            ),
            17 => 
            array (
                'id' => 21,
                'avatar' => '662d32c0db04a_pexels-simon-robben-614810.jpg',
                'firstName' => 'Plato',
                'lastName' => 'Fischer',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'muwekec@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$jMGy4..JJWb.jOXUfayq8OOHL.6BMo3KdfCe8LvlVuU1iyqz2FlzS',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:15:45',
                'updated_at' => '2024-04-27 17:15:45',
            ),
            18 => 
            array (
                'id' => 22,
                'avatar' => '662d32d986db0_photo.jpg',
                'firstName' => 'India',
                'lastName' => 'Wyatt',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'haxac@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$jqWKXcKcOrbQ7gLnKBOEs.k5hyslVQIkHgyL8LzZ78pJSDBZqhGWe',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:16:10',
                'updated_at' => '2024-04-27 17:16:10',
            ),
            19 => 
            array (
                'id' => 23,
                'avatar' => '662d32f898188_Photo gratuite close up portrait of cute young woman holding textbook.jpg',
                'firstName' => 'Lacy',
                'lastName' => 'Leonard',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 1,
                'email' => 'fyrinoho@mailinator.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$z8fggDuG6w7EK5dJ6IYnuuKkKxuzprCFB7wQ6zP//K5B/VcWwqBcG',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-27 17:16:41',
                'updated_at' => '2024-04-27 17:16:41',
            ),
            20 => 
            array (
                'id' => 24,
                'avatar' => 'avatar_47150435-eb7e-48a5-ae09-c36a3993fb8d.png',
                'firstName' => 'hassan',
                'lastName' => 'Elaasemy',
                'is_login' => 1,
                'is_popular' => 0,
                'password_change' => 0,
                'email' => 'elaasemyhassan01@gmail.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => 0,
                'profission' => 'dsvfefze',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Z3xUF.9YMuPGwk1vqV/jT.g9U7L3HietedJf9miOQ.ZIGPoCJAw5G',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-29 08:30:08',
                'updated_at' => '2024-04-29 13:38:16',
            ),
            21 => 
            array (
                'id' => 25,
                'avatar' => NULL,
                'firstName' => 'Niama',
                'lastName' => 'Mesmouki',
                'is_login' => 0,
                'is_popular' => 0,
                'password_change' => 0,
                'email' => 'niama.mesmouki@gmail.com',
                'datebirt' => NULL,
                'status_matrimonial' => NULL,
                'Numchild' => NULL,
                'profission' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$165Hydml927pKSYI0Q2xc.CRxqVT5M04E7n8UXvo5UUjIrhf9MWk.',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-04-29 11:21:36',
                'updated_at' => '2024-04-29 12:50:01',
            ), */
        ));
        
        
    }
}